"""production_baseline_v1_0_0

Revision ID: 252808427278
Revises: 
Create Date: 2025-08-06 10:59:58.894895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '252808427278'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create all tables for production baseline."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create users table
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('full_name', sa.String(), nullable=True),
        sa.Column('hashed_password', sa.String(), nullable=True),
        sa.Column('disabled', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    # Create contracts table
    op.create_table('contracts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('client_name', sa.String(), nullable=True),
        sa.Column('client_email', sa.String(), nullable=True),
        sa.Column('design_image_path', sa.String(), nullable=True),
        sa.Column('titulo_diseno', sa.String(), nullable=True),
        sa.Column('puesto_empresa', sa.String(), nullable=True),
        sa.Column('politica_confirmacion', sa.Text(), nullable=True),
        sa.Column('unsigned_pdf_path', sa.String(), nullable=True),
        sa.Column('signed_pdf_path', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('signed_at', sa.DateTime(), nullable=True),
        sa.Column('signer_ip', sa.String(), nullable=True),
        sa.Column('signer_user_agent', sa.String(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_client_email'), 'contracts', ['client_email'], unique=False)
    op.create_index(op.f('ix_contracts_client_name'), 'contracts', ['client_name'], unique=False)
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)

    # Create default_texts table
    op.create_table('default_texts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('key', sa.String(), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_default_texts_id'), 'default_texts', ['id'], unique=False)
    op.create_index(op.f('ix_default_texts_key'), 'default_texts', ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop all tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop default_texts table
    op.drop_index(op.f('ix_default_texts_key'), table_name='default_texts')
    op.drop_index(op.f('ix_default_texts_id'), table_name='default_texts')
    op.drop_table('default_texts')
    
    # Drop contracts table
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_client_name'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_client_email'), table_name='contracts')
    op.drop_table('contracts')
    
    # Drop users table
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    
    # ### end Alembic commands ###