"""Add new fields to contracts table

Revision ID: 2be0bed55c2e
Revises: 307df36a6412
Create Date: 2025-08-05 11:12:14.362501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be0bed55c2e'
down_revision: Union[str, Sequence[str], None] = '307df36a6412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_table('contracts')
    op.create_table('contracts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('client_name', sa.String(), nullable=True),
        sa.Column('client_email', sa.String(), nullable=True),
        sa.Column('design_image_path', sa.String(), nullable=True),
        sa.Column('photo_reference_path', sa.String(), nullable=True),
        sa.Column('unsigned_pdf_path', sa.String(), nullable=True),
        sa.Column('signed_pdf_path', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('signed_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_client_email'), 'contracts', ['client_email'], unique=False)
    op.create_index(op.f('ix_contracts_client_name'), 'contracts', ['client_name'], unique=False)
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('signed_file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_client_name'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_client_email'), table_name='contracts')
    op.alter_column('contracts', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('contracts', 'signed_pdf_path')
    op.drop_column('contracts', 'unsigned_pdf_path')
    op.drop_column('contracts', 'photo_reference_path')
    op.drop_column('contracts', 'design_image_path')
    # ### end Alembic commands ###
