"""add deleted_at field to contracts

Revision ID: 4204055852b8
Revises: 4344c91f9c85
Create Date: 2025-08-05 15:49:10.016832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4204055852b8'
down_revision: Union[str, Sequence[str], None] = '4344c91f9c85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'deleted_at')
    # ### end Alembic commands ###
