"""remove photo_reference_path column

Revision ID: 4344c91f9c85
Revises: d1511f041889
Create Date: 2025-08-05 15:26:57.071029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4344c91f9c85'
down_revision: Union[str, Sequence[str], None] = 'd1511f041889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'photo_reference_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('photo_reference_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
