"""Add traceability fields to contracts

Revision ID: d1511f041889
Revises: 2be0bed55c2e
Create Date: 2025-08-05 11:19:09.720219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1511f041889'
down_revision: Union[str, Sequence[str], None] = '2be0bed55c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('signer_ip', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('signer_user_agent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'signer_user_agent')
    op.drop_column('contracts', 'signer_ip')
    # ### end Alembic commands ###
