"""add new fields to contracts and create default texts table

Revision ID: fcfb3c6a59c9
Revises: 4204055852b8
Create Date: 2025-08-05 20:03:48.284516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcfb3c6a59c9'
down_revision: Union[str, Sequence[str], None] = '4204055852b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_default_texts_id'), 'default_texts', ['id'], unique=False)
    op.create_index(op.f('ix_default_texts_key'), 'default_texts', ['key'], unique=True)
    op.add_column('contracts', sa.Column('titulo_diseno', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('puesto_empresa', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('politica_confirmacion', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'politica_confirmacion')
    op.drop_column('contracts', 'puesto_empresa')
    op.drop_column('contracts', 'titulo_diseno')
    op.drop_index(op.f('ix_default_texts_key'), table_name='default_texts')
    op.drop_index(op.f('ix_default_texts_id'), table_name='default_texts')
    op.drop_table('default_texts')
    # ### end Alembic commands ###
